#!/usr/bin/env python
from os.path import join
from os.path import expanduser

from waflib.Configure import conf

top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_c')

    opt.add_option('--metis-inc', action='store', default='',
        help='Directory containing metis.h header.')

    opt.add_option('--metis-lib', action='store', default='',
        help='Directory containing metis library.')

def configure(conf):
    conf.load('compiler_c')
    metis_inc = expanduser(conf.options.metis_inc)
    metis_lib = expanduser(conf.options.metis_lib)
    conf.env.prepend_value('INCLUDES', [metis_inc])
    conf.env.prepend_value('LIBPATH', [metis_lib])
    conf.env.prepend_value('RPATH', [metis_lib])
    conf.check(header_name='metis.h', features='c cprogram')
    conf.check_cc(lib='metis')

def build(bld):

    bld.program(
        source = 'main.c',
        target = 'run-metis',
        lib  = ['metis',],
        cxxflags = ['-g','-O0'],
    )
