from waflib.Build import BuildContext
from waflib.Context import Context

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')

def build(bld):
    bld.recurse('src')
    bld.recurse('ft/a')
    bld.recurse('ft/b')

def test(ctx):
    print "root: test"
    ctx.recurse('ft/a')
    ctx.recurse('ft/b')

class TestContext(BuildContext):
    cmd = 'test'
    fun = 'test'
