#! /usr/bin/env python
# encoding: UTF-8
# Peter Forai
# Thomas Nagy, 2008

"""
Demonstrates how to create a c++ app that runs python scripts

Useful for apps providing script extensions
"""

VERSION='0.0.1'
APPNAME='swig_test'
top = '.'
out = 'build'

def options(opt):
	opt.load('g++ python')

def configure(conf):
	conf.load('g++ python')
	conf.check_python_version((2,4,2))
	conf.check_python_headers()

	conf.load('swig')
	if conf.check_swig_version() < (1, 2, 27):
		conf.fatal('this swig version is too old')

def build(bld):

	# embedding
	#
	# use swig_flags = '-c++ -python -dump_classes' for debugging

	obj = bld(
		features = 'cxx cxxprogram pyembed',
		source = 'embed/src1.cpp embed/bind.swig',
		target = 'embed/embed_demo',
		swig_flags = '-c++ -python -Wall',
		includes = '. embed')


	# extending
	#
	# be careful that the .py produced by swig is mandatory for using the library
	#
	# it is possible to disable 'mylib', and to add extend/a.cpp
	# to the source of extend/python/_test_swig_waf and remove use

	bld(
		features = 'cxx cxxshlib',
		source = 'extend/a.cpp',
		target = 'extend/mylib',
		includes = 'extend',
		export_includes = 'extend',
		vnum = '1.2.3',
		name = 'mylib')

	bld(
		features = 'cxx cxxshlib pyext',
		source = 'extend/python/test_swig_waf.i',
		target = 'extend/python/_test_swig_waf',
		swig_flags = '-c++ -python -Wall',
		includes = 'extend',
		vnum = '1.2.3',
		use  = 'mylib')

	bld.install_files('${PREFIX}/lib', 'extend/python/test_swig_waf.py')

	bld.add_post_fun(exec_test_python)

def exec_test_python(bld):
	import os, stat
	try:
		import subprocess
		proc = subprocess.Popen('''
PYTHONPATH=$PYTHONPATH:build/extend/python
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:build/extend/python:build/extend
python -c "import test_swig_waf; a=test_swig_waf.A(); print 'Testing: a.add(2, 3) ->', a.add(2, 3)"
'''.replace('\n', ' '), shell=True)
		proc.wait()
	except:
		pass

	# why does this fail now on mandriva???
	try:
		os.stat('build/embed/embed_demo')
		bld.cmd_and_log('PYTHONPATH=$PYTHONPATH:build/embed/ build/embed/embed_demo')
	except:
		pass

