package:
  name: waf-swig-demo
  version: 0.1.0

source:
  path: ..

requirements:
  build:
    - python
    - swig
    - waf
  run:
    - python

build:
  number: 0
  binary_relocation: true

test:
  commands:
    - ls

about:
  home: https://waf.io/
  summary: Waf SWIG demo
